# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap.api.inventory_api import InventoryApi


class TestInventoryApi(unittest.TestCase):
    """InventoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InventoryApi()

    def tearDown(self) -> None:
        pass

    def test_get_steam_inventory(self) -> None:
        """Test case for get_steam_inventory

        Get Steam Inventory
        """
        pass

    def test_get_steam_inventory_by_steam_id(self) -> None:
        """Test case for get_steam_inventory_by_steam_id

        Get Steam Inventory by Steam ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
