# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap.api.portfolio_api import PortfolioApi


class TestPortfolioApi(unittest.TestCase):
    """PortfolioApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PortfolioApi()

    def tearDown(self) -> None:
        pass

    def test_add_item_to_portfolio(self) -> None:
        """Test case for add_item_to_portfolio

        Add Item to Portfolio
        """
        pass

    def test_add_transaction(self) -> None:
        """Test case for add_transaction

        Add Transaction
        """
        pass

    def test_create_portfolio(self) -> None:
        """Test case for create_portfolio

        Create Portfolio
        """
        pass

    def test_delete_portfolio(self) -> None:
        """Test case for delete_portfolio

        Delete Portfolio
        """
        pass

    def test_delete_transaction(self) -> None:
        """Test case for delete_transaction

        Delete Transaction
        """
        pass

    def test_get_portfolio_value(self) -> None:
        """Test case for get_portfolio_value

        Get Portfolio Value
        """
        pass

    def test_get_portfolio_value_history(self) -> None:
        """Test case for get_portfolio_value_history

        Get Portfolio Value History
        """
        pass

    def test_import_steam_inventory(self) -> None:
        """Test case for import_steam_inventory

        Import Steam Inventory
        """
        pass

    def test_list_portfolio_items(self) -> None:
        """Test case for list_portfolio_items

        List Portfolio Items
        """
        pass

    def test_list_portfolios(self) -> None:
        """Test case for list_portfolios

        List Portfolios
        """
        pass

    def test_list_transactions(self) -> None:
        """Test case for list_transactions

        List Transactions
        """
        pass

    def test_remove_item_from_portfolio(self) -> None:
        """Test case for remove_item_from_portfolio

        Remove Item from Portfolio
        """
        pass

    def test_update_transaction(self) -> None:
        """Test case for update_transaction

        Update Transaction
        """
        pass

    def test_value_portfolio(self) -> None:
        """Test case for value_portfolio

        Value Portfolio
        """
        pass


if __name__ == '__main__':
    unittest.main()
