# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cs2cap.models.market_history_chart_point import MarketHistoryChartPoint

class TestMarketHistoryChartPoint(unittest.TestCase):
    """MarketHistoryChartPoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketHistoryChartPoint:
        """Test MarketHistoryChartPoint
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketHistoryChartPoint`
        """
        model = MarketHistoryChartPoint()
        if include_optional:
            return MarketHistoryChartPoint(
                t = 56,
                price = 56,
                qty = 56
            )
        else:
            return MarketHistoryChartPoint(
                t = 56,
                price = 56,
        )
        """

    def testMarketHistoryChartPoint(self):
        """Test MarketHistoryChartPoint"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
