# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cs2cap.models.batch_price_quote import BatchPriceQuote
from typing import Optional, Set
from typing_extensions import Self

class PortfolioLineItem(BaseModel):
    """
    Valuation line item for one portfolio entry.
    """ # noqa: E501
    item_id: StrictInt = Field(description="Normalized catalog item ID used by this API.")
    market_hash_name: StrictStr = Field(description="Canonical Steam market hash name for the item.")
    phase: Optional[StrictStr] = None
    quantity: StrictInt = Field(description="Number of units held.")
    best_ask: Optional[StrictInt] = None
    best_bid: Optional[StrictInt] = None
    item_value: Optional[StrictInt] = None
    image_url: Optional[StrictStr] = None
    rarity_name: Optional[StrictStr] = None
    rarity_color: Optional[StrictStr] = None
    providers: Optional[List[BatchPriceQuote]] = Field(default=None, description="Per-provider price quotes.")
    __properties: ClassVar[List[str]] = ["item_id", "market_hash_name", "phase", "quantity", "best_ask", "best_bid", "item_value", "image_url", "rarity_name", "rarity_color", "providers"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PortfolioLineItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in providers (list)
        _items = []
        if self.providers:
            for _item_providers in self.providers:
                if _item_providers:
                    _items.append(_item_providers.to_dict())
            _dict['providers'] = _items
        # set to None if phase (nullable) is None
        # and model_fields_set contains the field
        if self.phase is None and "phase" in self.model_fields_set:
            _dict['phase'] = None

        # set to None if best_ask (nullable) is None
        # and model_fields_set contains the field
        if self.best_ask is None and "best_ask" in self.model_fields_set:
            _dict['best_ask'] = None

        # set to None if best_bid (nullable) is None
        # and model_fields_set contains the field
        if self.best_bid is None and "best_bid" in self.model_fields_set:
            _dict['best_bid'] = None

        # set to None if item_value (nullable) is None
        # and model_fields_set contains the field
        if self.item_value is None and "item_value" in self.model_fields_set:
            _dict['item_value'] = None

        # set to None if image_url (nullable) is None
        # and model_fields_set contains the field
        if self.image_url is None and "image_url" in self.model_fields_set:
            _dict['image_url'] = None

        # set to None if rarity_name (nullable) is None
        # and model_fields_set contains the field
        if self.rarity_name is None and "rarity_name" in self.model_fields_set:
            _dict['rarity_name'] = None

        # set to None if rarity_color (nullable) is None
        # and model_fields_set contains the field
        if self.rarity_color is None and "rarity_color" in self.model_fields_set:
            _dict['rarity_color'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PortfolioLineItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "item_id": obj.get("item_id"),
            "market_hash_name": obj.get("market_hash_name"),
            "phase": obj.get("phase"),
            "quantity": obj.get("quantity"),
            "best_ask": obj.get("best_ask"),
            "best_bid": obj.get("best_bid"),
            "item_value": obj.get("item_value"),
            "image_url": obj.get("image_url"),
            "rarity_name": obj.get("rarity_name"),
            "rarity_color": obj.get("rarity_color"),
            "providers": [BatchPriceQuote.from_dict(_item) for _item in obj["providers"]] if obj.get("providers") is not None else None
        })
        return _obj


