# coding: utf-8

"""
    CS2Cap

    CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class SalesFiltersMeta(BaseModel):
    """
    Filter metadata for sales endpoint.
    """ # noqa: E501
    item_id: Optional[StrictInt] = None
    market_hash_name: Optional[StrictStr] = None
    phase: Optional[StrictStr] = None
    requested_providers: Optional[List[StrictStr]] = None
    min_float: Optional[Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = None
    max_float: Optional[Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = None
    paint_seed: Optional[Annotated[int, Field(le=1000, strict=True, ge=0)]] = None
    stickers: Optional[List[StrictStr]] = None
    charms: Optional[StrictStr] = None
    limit: Annotated[int, Field(le=1000, strict=True, ge=1)] = Field(description="Maximum number of records returned per page.")
    __properties: ClassVar[List[str]] = ["item_id", "market_hash_name", "phase", "requested_providers", "min_float", "max_float", "paint_seed", "stickers", "charms", "limit"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SalesFiltersMeta from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if item_id (nullable) is None
        # and model_fields_set contains the field
        if self.item_id is None and "item_id" in self.model_fields_set:
            _dict['item_id'] = None

        # set to None if market_hash_name (nullable) is None
        # and model_fields_set contains the field
        if self.market_hash_name is None and "market_hash_name" in self.model_fields_set:
            _dict['market_hash_name'] = None

        # set to None if phase (nullable) is None
        # and model_fields_set contains the field
        if self.phase is None and "phase" in self.model_fields_set:
            _dict['phase'] = None

        # set to None if requested_providers (nullable) is None
        # and model_fields_set contains the field
        if self.requested_providers is None and "requested_providers" in self.model_fields_set:
            _dict['requested_providers'] = None

        # set to None if min_float (nullable) is None
        # and model_fields_set contains the field
        if self.min_float is None and "min_float" in self.model_fields_set:
            _dict['min_float'] = None

        # set to None if max_float (nullable) is None
        # and model_fields_set contains the field
        if self.max_float is None and "max_float" in self.model_fields_set:
            _dict['max_float'] = None

        # set to None if paint_seed (nullable) is None
        # and model_fields_set contains the field
        if self.paint_seed is None and "paint_seed" in self.model_fields_set:
            _dict['paint_seed'] = None

        # set to None if stickers (nullable) is None
        # and model_fields_set contains the field
        if self.stickers is None and "stickers" in self.model_fields_set:
            _dict['stickers'] = None

        # set to None if charms (nullable) is None
        # and model_fields_set contains the field
        if self.charms is None and "charms" in self.model_fields_set:
            _dict['charms'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SalesFiltersMeta from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "item_id": obj.get("item_id"),
            "market_hash_name": obj.get("market_hash_name"),
            "phase": obj.get("phase"),
            "requested_providers": obj.get("requested_providers"),
            "min_float": obj.get("min_float"),
            "max_float": obj.get("max_float"),
            "paint_seed": obj.get("paint_seed"),
            "stickers": obj.get("stickers"),
            "charms": obj.get("charms"),
            "limit": obj.get("limit")
        })
        return _obj


